init:
    packer init noble/noble.pkr.hcl

base: init
    packer build noble/noble.pkr.hcl

services: base
    packer build syncthing/syncthing.pkr.hcl
    packer build grafana/grafana.pkr.hcl
    packer build prometheus/prometheus.pkr.hcl


syncthing: 
    packer build syncthing/syncthing.pkr.hcl

grafana: 
    packer build grafana/grafana.pkr.hcl

prometheus: 
    packer build prometheus/prometheus.pkr.hcl




