---
- name: Install incus client on Ubuntu 24.04
  hosts: glrunner
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download zabbly GPG key
      get_url:
        url: https://pkgs.zabbly.com/key.asc
        dest: /etc/apt/keyrings/zabbly.asc
        mode: '0644'

    - name: Add zabbly repository for incus
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/zabbly.asc arch=amd64] https://pkgs.zabbly.com/incus/stable noble main"
        state: present
        filename: zabbly-incus

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install incus client
      apt:
        name: incus-client
        state: present