---
- name: Install OpenTofu client on Ubuntu 24.04
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download OpenTofu GPG key
      get_url:
        url: https://packages.opentofu.org/opentofu/tofu/gpgkey
        dest: /etc/apt/keyrings/opentofu.asc
        mode: '0644'

    - name: Add OpenTofu repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/opentofu.asc] https://packages.opentofu.org/opentofu/tofu/any/ any main"
        state: present
        filename: opentofu

    - name: Add OpenTofu source repository
      apt_repository:
        repo: "deb-src [signed-by=/etc/apt/keyrings/opentofu.asc] https://packages.opentofu.org/opentofu/tofu/any/ any main"
        state: present
        filename: opentofu-src

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenTofu
      apt:
        name: tofu
        state: present