- import_playbook: books/local.early.yaml

- import_playbook: books/update-packages.yaml
- import_playbook: books/iscsi.yaml

- import_playbook: books/groups.yaml

- name: Install and configure Incus and its whole stack
  hosts: selfie
  collections:
    - lxc.incus
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "default_ipv4"
    - "default_ipv6"
    - "distribution_release"
  any_errors_fatal: true
  vars:
    config_root_dir: "{{ '.' | ansible.builtin.realpath }}"
  roles:
    - role: system_settings
    - role: netplan
    - role: ntp
    - role: incus

- import_playbook: books/local.late.yaml
